version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "8501:8501"  # Zmień z 8000:8000 na 8501:8501
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - ENV=production
    restart: unless-stopped