version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "8501:8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - ENV=production
    restart: unless-stopped