services:
  aironick:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BASE_URL=${STREAMLIT_BASE_URL:-}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    restart: unless-stopped
    container_name: aironick-app